# Generated by Django 3.1.1 on 2020-09-07 18:09

from django.db import migrations, models
import survey.models.response


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20200609_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='pin',
            field=models.CharField(default=survey.models.response.get_pin, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('pin',)},
        ),
    ]
